-- 配置中心表
CREATE TABLE IF NOT EXISTS configs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    service VARCHAR(64) NOT NULL COMMENT '服务名',
    `key` VARCHAR(128) NOT NULL COMMENT '配置键',
    value TEXT NOT NULL COMMENT '配置值（JSON格式，可能为密文）',
    encrypted TINYINT NOT NULL DEFAULT 0 COMMENT '是否加密: 0=明文, 1=密文',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_service_key (service, `key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配置中心';
